### ISSUE TITLE
Extract Method action is not working

### ISSUE THREAD

**Issue by istocniks** [ignatov/intellij-erlang#591] opened 2015-04-14 21:39 UTC
IDEA 14.1.1, Erlang 8b01793118041c835be805d2f3cb67b64e081f78

```erlang
test_extract() ->
    Nodes = nodes(),
    io:format("Nodes: ~p", [Nodes]).
```

Nothing happens when I put a caret on ```nodes()``` and do Refactor–>Extract–>Method...
I remember it was working on a stable version of the plugin.

**Comment by deadok22** [comment] 2015-04-30 13:55
Can't reproduce neither on master, nor on https://github.com/ignatov/intellij-erlang/commit/8b01793118041c835be805d2f3cb67b64e081f78

**Comment by istocniks** [comment] 2015-04-30 17:39
This should help:
```
 Marker - Apr 30, 2015, 10:39:26 AM
2015-04-30 10:39:32,110 [ 644533]  ERROR - llij.ide.plugins.PluginManager - null 
java.lang.NullPointerException
	at org.intellij.erlang.refactoring.introduce.ErlangExtractFunctionDialog.<init>(ErlangExtractFunctionDialog.java:41)
	at org.intellij.erlang.refactoring.introduce.ErlangExtractFunctionHandler.perform(ErlangExtractFunctionHandler.java:160)
	at org.intellij.erlang.refactoring.introduce.ErlangExtractFunctionHandler.access$100(ErlangExtractFunctionHandler.java:58)
	at org.intellij.erlang.refactoring.introduce.ErlangExtractFunctionHandler$1.process(ErlangExtractFunctionHandler.java:97)
	at org.intellij.erlang.refactoring.ErlangRefactoringUtil.smartIntroduce(ErlangRefactoringUtil.java:110)
	at org.intellij.erlang.refactoring.introduce.ErlangExtractFunctionHandler.invoke(ErlangExtractFunctionHandler.java:84)
	at com.intellij.refactoring.actions.BaseRefactoringAction.actionPerformed(BaseRefactoringAction.java:122)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher$3.performAction(IdeKeyEventDispatcher.java:586)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:637)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.d(IdeKeyEventDispatcher.java:476)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.dispatchKeyEvent(IdeKeyEventDispatcher.java:212)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:538)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:382)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:296)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:211)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:196)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:188)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:122)
2015-04-30 10:39:32,111 [ 644534]  ERROR - llij.ide.plugins.PluginManager - IntelliJ IDEA 14.1.2  Build #IU-141.713.2 
2015-04-30 10:39:32,111 [ 644534]  ERROR - llij.ide.plugins.PluginManager - JDK: 1.6.0_65 
2015-04-30 10:39:32,111 [ 644534]  ERROR - llij.ide.plugins.PluginManager - VM: Java HotSpot(TM) 64-Bit Server VM 
2015-04-30 10:39:32,111 [ 644534]  ERROR - llij.ide.plugins.PluginManager - Vendor: Apple Inc. 
2015-04-30 10:39:32,111 [ 644534]  ERROR - llij.ide.plugins.PluginManager - OS: Mac OS X 
2015-04-30 10:39:32,111 [ 644534]  ERROR - llij.ide.plugins.PluginManager - Last Action: ExtractMethod 
```

**Comment by deadok22** [comment] 2015-05-24 12:24
It's a duplicate of #596 and is due to your plugin was built with UI Designer plugin disabled.

**Closed by deadok22** 2015-05-24 12:24 UTC
