### ISSUE TITLE
rebar3 support

### ISSUE THREAD

**Issue by sergium** [ignatov/intellij-erlang#704] opened 2015-11-22 02:23 UTC
Would be great to support rebar3

**Comment by marco-m** [comment] 2015-11-22 17:22
+1 :-)

**Comment by tsloughter** [comment] 2015-11-24 00:47
:+1:

**Comment by tsloughter** [comment] 2015-11-24 13:18
Also, I'd be happy to help however I can. I don't actually use intellij but I do work on rebar3.

**Comment by marco-m** [comment] 2015-12-21 20:27
I just posted a $20 bounty for this ticket https://www.bountysource.com/issues/28505949-rebar3-support
This means:
1. if anybody adds rebar3 supports and the pull request gets accepted, he/she gets $20
2. Anybody can add more money to the bounty :-)

**Comment by marco-m** [comment] 2015-12-21 22:39
Wow, we are already at $120! Thanks @bryanhughes

**Comment by sparr** [comment] 2015-12-21 22:49
The people upping the bounty should post here what "support" means to them. This is a really vague request.

**Comment by marco-m** [comment] 2015-12-21 22:56
@sparr, well, as you probably know, intellij-erlang supports rebar2. So we are talking about the same support, but for rebar3. To me it is really clear, not vague at all. Anyway, at least it should support using rebar3 for building and running eunit.

**Comment by sparr** [comment] 2015-12-21 23:00
An equal level of support to the existing rebar2 support might seem clear/obvious, but it's not. Just enough for building would be "support". As would enough for running eunit, escriptize, or other rebar tools. Etc.

**Comment by marco-m** [comment] 2015-12-22 12:31
We are at $140! Thanks @byaruhaf

**Comment by CyborTronik** [comment] 2016-01-07 15:42
Not able to debug eunit with rebar3 :/

**Comment by saleyn** [comment] 2016-01-14 14:42
:+1:

**Comment by henry-hz** [comment] 2016-01-20 07:56
yeah i want

**Comment by marco-m** [comment] 2016-01-20 17:51
We are at [![Bountysource](https://api.bountysource.com/badge/issue?issue_id=28505949)](https://www.bountysource.com/issues/28505949-rebar3-support?utm_source=28505949&utm_medium=shield&utm_campaign=ISSUE_BADGE)
Thanks to all involved! :-)

**Comment by benoitc** [comment] 2016-02-26 19:33
what's the status?

**Comment by ignatov** [comment] 2016-02-26 20:40
$250 :–)

**Comment by marco-m** [comment] 2016-02-26 21:21
salut Benoit, any chance for you to add to the tip jar over at bountysource? Or spread the world that we are collecting money for this? merci!

**Comment by ignatov** [comment] 2016-02-26 21:40
Guys, I'm really want to improve the plugin but I have no time for it right now.
BTW, I'm looking for a student for internship program who will be responsible to the plugin. Please keep calm!

**Comment by marco-m** [comment] 2016-02-27 08:38
Hello Sergey,
Since I found the plugin so useful, I wanted to give back a small something, I didn't want to put pressure on you :-)
Thanks again for all your work, and if you manage to find an intern, that would be very nice!

**Comment by msilvestre** [comment] 2016-03-24 15:06
I am trying to debug a erlang application built under rebar3. From this issue it seams it is impossible at the moment right?

PS. I am using OSX.

Thanks.

**Comment by deadok22** [comment] 2016-03-27 20:56
@msilvestre regardless of what you build your application with, you can debug it with this plugin if the following holds:
1) debug_info was set upon compilation
2) source path is present in beam's metadata (see your_module:module_info())

To debug an application built by an external build system, remove 'Make' from 'Before launch' section in a run configuration you want to debug. Also, make sure that code path is set in this run configuration - if something is missing, add it with it with '-pa ...' in "Flags for 'erl'" text field.

**Comment by msilvestre** [comment] 2016-03-28 09:36
HI,

Thanks for the help.
I am not getting it.

What do you mean by code path? Is it working path? Regarding ht -pa option,
I don't even know what directory or directories should put on it. We are
using rebar3 and so just need to run the generated script.

PS. As you probably notice I am new to erlang, so sorry for any dumb/newbie
stuff.

Here is a partial tree of my project, I hope this can help:
.
├── CHANGELOG.md
├── Makefile
├── RELEASE_PROTOCOL.md
├── UPGRADE.md
├── _build
│   └── default
│       ├── deps
│       ├── plugins
│       └── rel
│           ├── erl_crash.dump
│           └── mine
│               ├── Mnesia.mine@XXX-00770.company.global
│               ├── bin
│               ├── etc
│               ├── infrastructure
│               ├── leader_mine@XXX-00770.company.global
│               ├── lib
│               ├── log
│               └── release
├── apps
│   └── mine
│       ├── _build
│       │   └── default
│       │       └── lib
│       │           └── mine
│       │               ├── include -> ../../../../include
│       │               ├── priv -> ../../../../priv
│       │               └── src -> ../../../../src
│       ├── include
│       ├── proto
│       │   └── mineƒ.proto
│       ├── rebar.config
│       ├── rebar.config.script
│       ├── schemas
│       │   └── goliath.json
│       └── src
├── client
│   ├── Makefile
│   ├── client
│   └── framework
├── cmp_rel
├── config
│   ├── app.config
│   ├── custom.config
│   ├── goliath.config
│   ├── infrastructure.config.ini
│   ├── infrastructure.custom.json
│   ├── k9.config
│   ├── leaderboards.config
│   ├── matchmaker.config
│   ├── omniata.config
│   ├── overlays
│   │   ├── dev
│   │   ├── infrastructure.config
│   │   ├── live
│   │   ├── loadtest
│   │   ├── local
│   │   └── staging
│   ├── push_notifications.config
│   ├── restore.config
│   ├── reward-callback.config
│   ├── safety_valve.config
│   ├── spins.config
│   ├── surprise_packs.config
│   ├── version.config
│   └── vm.args
├── elvis.config
├── etc
│   ├── as3_crossdomain_policy.xml
│   ├── mine.init.sh
│   ├── mine_cert.pem
│   ├── mine_key.pem
│   └── ssh
│       └── setup
├── mine-aws-credentials
├── mine-server.iml
├── infrastructure
├── latest.txt
├── rebar.config
├── rebar.config.lock
├── rebar.config.script
├── rebar.lock
├── rebar3
└── scripts
    ├── appups
    ├── appups.modules
    ├── config
    ├── current.version
    ├── deploy
    ├── install
    ├── keys
    ├── lib.link.sh
    ├── lib.unlink.sh
    ├── opsworks.create.app.sh
    ├── prepare_deploy.sh
    ├── release
    └── version

--
Miguel Silvestre

**Comment by deadok22** [comment] 2016-03-29 03:49
@msilvestre, you can read about code path [here](http://erlang.org/doc/man/code.html).

**Comment by zyuyou** [comment] 2016-03-30 10:31
Hi guys! I' m working on rebar3 support. I have create a new `external model`([Rebar3ImportProjectBuilder](https://github.com/zyuyou/intellij-erlang/blob/rebar3_support/src/org/intellij/erlang/rebar/importWizard/Rebar3ProjectImportBuilder.java))  only for `Rebar3`. but there are still much work to do for supporting `Rebar3` goodly. You can follow [this repo](https://github.com/zyuyou/intellij-erlang-rebar3-test-distributions) to download the latest test version. Create an issue to tell me which feature should be fixed for supporting for `Rebar3`.

**Comment by marco-m** [comment] 2016-04-04 20:53
Probably best way to integrate rebar3 is via this plugin https://github.com/ferd/rebar3_shellrpc, that gets it completely right! Since rebar2/3 needs the Erlang VM, it takes a lot of time (around 1 sec) just to start. The plugin allows an IDE to interface with a running rebar3 operating system process, cutting the startup time to almost zero!

**Comment by zyuyou** [comment] 2016-04-13 05:33
@marco-m I think your idea for cutting the startup time of Erlang VM need **Rebar3** to support `rebar3 --daemon` which like `gradle --daemon`, but the plugin https://github.com/ferd/rebar3_shellrpc can't do this.

**Comment by zyuyou** [comment] 2016-04-14 15:58
@ignatov Is that making `Rebar3` as an externalSystem which like `Gradle` in IDEA possible?I'm trying that, but also had some difficulties about `In-Process` and `Out-of-Process`. Although I will figure it out, I want to make sure that is possible. Did you try that before using `jps-builder`?

**Comment by marco-m** [comment] 2016-04-18 18:50
We are at 300$, thanks byaruhaf!

**Comment by benoitc** [comment] 2016-05-13 19:25
just checking but what is the current status of the port of rebar3. Anything I can help in testing?

**Comment by marco-m** [comment] 2016-07-29 07:45
Hello Sergey,
any news about finding an intern to work on rebar3 support? :-)

**Comment by ignatov** [comment] 2016-07-29 08:04
Hi Marco,
I'm a bit busy right now, but I'd like to spend one autumn raining weekend for this.

**Comment by marco-m** [comment] 2016-07-29 09:31
Thanks for the quick reply. Enjoy the summer then :-)

**Comment by coolfeature** [comment] 2016-08-23 06:52
+1 rebar3 support would be really nice

**Comment by binarytemple** [comment] 2016-09-28 22:23
+1 <<" ![filthy lucre](https://camo.githubusercontent.com/eb6e7e556585919206fdac149c7d4472f8198aa9/68747470733a2f2f6170692e626f756e7479736f757263652e636f6d2f62616467652f69737375653f69737375655f69643d3238353035393439) ">>

**Comment by marco-m** [comment] 2016-11-17 20:21
Hello Sergey,
any news? Could the community do anything to help?

**Comment by ignatov** [comment] 2016-11-17 20:31
Hi @marco-m! Will be really cool to have a prioritized list of features about rebar 3.

**Comment by binarytemple** [comment] 2016-11-17 22:06
Perhaps it's better to just write a rebar 3 plugin that generates the
Intellij configuration files? That builds on top of the really good project
build support in Intellij and creates a good path to supporting multiple
IDE better?

**Comment by benoitc** [comment] 2017-01-13 10:51
@ignatov any ETA about i?

about some prioritized feature list I would propose the following:

1. handle dependencies from hex.pm
2. rebar3 eunit command
3. rebar3 ct command
4. rebar3 dialyzer command line support
5. rebar3 release command support
6. uses rebar3 shell as an option

**Comment by ignatov** [comment] 2017-01-21 20:27
Hooray everybody, I've imported the rebar 3 project with the brand new rebar 3 importer:
<img width="798" alt="screenshot 2017-01-21 22 44 38" src="https://cloud.githubusercontent.com/assets/426890/22177379/7438489c-e02d-11e6-8002-f0082e5658f8.png">

If you'd like to test it, please download the latest [build](https://teamcity.jetbrains.com/repository/download/IntellijIdeaPlugins_IntellijErlang_Tests/971825:id/Erlang-0.9.923.zip?guest=1).

**Comment by binarytemple** [comment] 2017-01-21 21:55
Nice

**Comment by tsloughter** [comment] 2017-01-22 00:40
@ignatov great!

Is there someone I should put issues, assuming if you want them yet? Like it finds the rebar3 in my path, but because I use `rebar3 local install` it isn't an escript but it still tries to run it with escript, so it fails to run rebar3. Would be great if it either checked the type of he file or simply executed it instead of passing to escript.

**Comment by ignatov** [comment] 2017-01-22 05:34
@tsloughter Feel free to open issues, but in my installation rebar3 is an escript:
```
rebar3 > head ~/bin/rebar3                                                                                                                                                 master
#!/usr/bin/env escript
%%
%%! +sbtu +A0
PK
```

**Comment by ignatov** [comment] 2017-01-22 07:07
BTW, do you know is it possible to run rebar3 on Windows? I've tried to run it but failed.

**Comment by marco-m** [comment] 2017-01-22 16:43
Hehe, I am very happy, thanks Sergey! I'll try it out :-) 🍾

**Comment by tsloughter** [comment] 2017-01-22 17:32
It does work on windows.

@ignatov yes, downloaded rebar3 is an escript. But it has support for unpacking itself with `rebar3 local install` which gives a shell script in `~/.cache/rebar3/bin`. This is both a little faster to run and doesn't have the issue the escript has when you `ctrl-c` out of `rebar3 shell` where it can screw up your terminal until a `reset`.

**Comment by ignatov** [comment] 2017-01-22 17:35
I'm glad to hear, that it works on Windows. Please use the latest plugin
build and tell me what's good and what's wrong.

**Comment by benoitc** [comment] 2017-01-22 20:46
@ignatov using the rebar3 escript, compilation works. However using rebar3 from ~/.cache/rebar3/bin doesn't work even on latest artefact from team city .Maybe the usage of escript could be discarded?

**Comment by binarytemple** [comment] 2017-01-22 21:06
I would imagine for most people the escript would be more idiomatic. Using
rebar3 for months now and was not even aware it could be installed in that
manner.

**Comment by marco-m** [comment] 2017-01-23 06:25
If I follow the link to the latest pre-release build from the README.md, I get a 404 not found error. 

If I follow the link in the previous version of README.md, https://teamcity.jetbrains.com/project.html?projectId=IntellijIdeaPlugins_Erlang&tab=projectOverview, then I can select either the last build (that now has some failing tests) or go browse the history and select the last successful build (925).

Maybe another approach is to point directly to the history of builds:
https://teamcity.jetbrains.com/viewType.html?buildTypeId=IntellijIdeaPlugins_IntellijErlang_Tests&tab=buildTypeHistoryList

thanks!

**Comment by marco-m** [comment] 2017-02-01 17:45
Hello Sergey, I am really happy with the support for rebar3, thanks again :-)

I found a blocker bug for me: with eunit tests driven by rebar3, in case of test failure or compilation failure, the plugin is confused and opens the file below `build` instead than the real source file. I opened #780 to explain.

**Comment by ignatov** [comment] 2017-02-01 18:15
@marco-m will see, thanks.

**Comment by marco-m** [comment] 2017-03-12 07:05
Hello all bug bounty backers (see [![Bountysource](https://api.bountysource.com/badge/issue?issue_id=28505949)](https://www.bountysource.com/issues/28505949-rebar3-support?utm_source=28505949&utm_medium=shield&utm_campaign=ISSUE_BADGE)),

After realising that #780 (rebar3 prints paths containing `_build`) is a bug of rebar3 and not a bug due to how intellij-erlang interprets it, I think we (the bakers) should be happy enough with rebar3 support and give Sergey a small token of appreciation by releasing the bounty on this PR :-) 

I use the plugin daily with rebar3 (both compile and eunit) and it is good enough in my opinion.

Let's not forget that this is also the first bounty ever (I think) on intellij-rebar, so it is a small way to say "Thank you" to Sergey and the other contributors for this wonderful plugin :-)

So on my side I would invite @ignatov to claim the bounty on the bountysource site.

Thanks everybody involved :-)

**Comment by marco-m** [comment] 2017-03-12 08:14
Good question indeed :-) Reading https://github.com/bountysource/core/wiki/Frequently-Asked-Questions, in my understanding this issue (#704) must be closed as done here on github. Then you can claim the bounty on the bountysource web site, then the backers need to accept the claim. It is the first time I am using bountysource, so I am discovering this process with you :-)

**Closed** 2017-03-12 09:01 UTC

**Comment by marco-m** [comment] 2017-03-12 09:07
I accepted the claim. From bountysource documentation, the money will be made available when all the backers have accepted or after 2 weeks in case of inactivity. Thanks again!

**Comment by ignatov** [comment] 2017-03-12 09:08
@marco-m Thank you! Will see ;)

**Comment by sergium** [comment] 2017-03-12 09:13
accepted)

@ignatov - thanks Sergey!

**Comment by tsloughter** [comment] 2017-03-12 17:18
accepting.

But what is the issue with the build path? I'd really prefer not to ever have to change that in rebar3 :). It should be a symlink so opening the file from that path shouldn't be an issue? If it is then I'd suggest parsing the output and finding the corresponding source file based on the basename.

Maybe we'll see a simple way to fix this in rebar3 but I don't expect to, at least not anytime soon.

**Comment by marco-m** [comment] 2017-03-12 20:16
@tsloughter Please see erlang/rebar3#1464 for the gory details :-)

**Comment by binarytemple** [comment] 2017-03-13 00:21
Accepted

**Comment by marco-m** [comment] 2017-03-26 18:54
I just received a notification from BountySource, the bounty has been paid :-)
