### ISSUE TITLE
incorrect unbound variable error msg

### ISSUE THREAD

**Issue by icyocean** [ignatov/intellij-erlang#498] opened 2014-09-25 07:47 UTC
For the following code the IDE gives a "Variable 'B' is unbound" msg which is incorrect:

f(A) ->
    case A of
        _ ->
            B = A
    end,
    case B of
        _ ->
            B %%Variable 'B' unbound
    end.

**Comment by kvakvs** [comment] 2019-08-01 09:13
This is a duplicate of #819
Thank you for reporting

**Closed by kvakvs** 2019-08-01 09:13 UTC
