### ISSUE TITLE
fun() inner formatting issue

### ISSUE THREAD

**Issue by bryanhughes** [ignatov/intellij-erlang#461] opened 2014-03-24 20:39 UTC
Have all the Alignment options checked.  Installed the latest build 548.

``` erlang
        MFun = fun() ->
            % Force the setting of the data point 
            case gomachine_device:set_datapoint(DeviceID, Datapoint) of
                {ok, _} ->
                    ok;
                _Reason ->
                    ok
            end
               end,
        MFun(),
```

The fun() / end aligns correctly, but the inner block of code does not. In the example above, its the case but generally happens to all lines.

Would expect it to be:

``` erlang
        MFun = fun() ->
                    % Force the setting of the data point 
                    case gomachine_device:set_datapoint(DeviceID, Datapoint) of
                        {ok, _} ->
                            ok;
                        _Reason ->
                            ok
                    end
               end,
        MFun(),
```

**Comment by kvakvs** [comment] 2019-08-01 13:51
Closing this as Duplicate of #707
Thanks for reporting

**Closed by kvakvs** 2019-08-01 13:51 UTC
Labels: feat:Formatter
