### ISSUE TITLE
Wrong unused/unexpetced with case statement

### ISSUE THREAD

**Issue by rs7** [ignatov/intellij-erlang#766] opened 2016-09-18 10:56 UTC
![screenshot_22](https://cloud.githubusercontent.com/assets/971343/18615147/f79c8d32-7dc8-11e6-8aa9-f49143e043e5.png)
![screenshot_23](https://cloud.githubusercontent.com/assets/971343/18615148/f7d36622-7dc8-11e6-94a8-f38b17f91eba.png)

> Version: 0.8.901

**Comment by ignatov** [comment] 2016-09-18 13:56
Please add a comma after end.

**Comment by rs7** [comment] 2016-09-19 04:53
Sorry, wrong sample. This another one.
![screenshot_26](https://cloud.githubusercontent.com/assets/971343/18622862/a68ab4ae-7e5f-11e6-8e1e-c3a940893a69.png)

**Comment by ignatov** [comment] 2016-09-19 06:04
That's a good catch, thanks for reporting.

**Comment by kvakvs** [comment] 2019-08-01 09:05
This is a duplicate of #819
Thank you for reporting

**Closed by kvakvs** 2019-08-01 09:05 UTC
Labels: duplicate
