### ISSUE TITLE
Concatenation of ?MODULE_STRING macro is not recognized by the parser

### ISSUE THREAD

**Issue by saleyn** [ignatov/intellij-erlang#715] opened 2016-01-22 02:28 UTC
The following is a valid Erlang syntax:
```
Term = list_to_atom("abc." ?MODULE_STRING).
```
but the `intellij-erlang` plugin gets confused.

**Comment by deadok22** [comment] 2016-01-31 10:37
Thank you for reporting, @saleyn.

The issue is fixed in the latest build at https://teamcity.jetbrains.com/project.html?projectId=IntellijIdeaPlugins_Erlang&tab=projectOverview

**Closed by deadok22** 2016-01-31 10:37 UTC

**Comment by saleyn** [comment] 2016-01-31 14:31
Thank you!

**Comment by saleyn** [comment] 2016-01-31 15:53
Could you please update the releases page:
https://github.com/ignatov/intellij-erlang/releases

**Comment by deadok22** [comment] 2016-02-01 14:29
@ignatov should we get rid of /releases page now that we have teamcity building the plugin?

**Comment by ignatov** [comment] 2016-02-01 15:23
@deadok22 We can do it, but I need to check that CI produced artifacts with the appropriate build number.

**Comment by saleyn** [comment] 2016-02-01 18:30
If that page is obsolete, what is the proper location to download built pre-releases?  The [other link](https://www.dropbox.com/sh/4sbgxzjto5fa21b/1cpM3Nb-yF) mentioned in the README.md shows no updates in the past 2 years.

**Comment by deadok22** [comment] 2016-02-07 08:35
@saleyn, the latest build can be obtained from [this page](https://teamcity.jetbrains.com/project.html?projectId=IntellijIdeaPlugins_Erlang&tab=projectOverview). I'll update the readme. Thanks!

**Comment by saleyn** [comment] 2016-02-09 20:37
@deadok22, when you login to the [given page](https://teamcity.jetbrains.com/project.html?projectId=IntellijIdeaPlugins_Erlang&tab=projectOverview) as guest, there's no link to the zip download.  I haven't tried creating an account there, but is it necessary to get the zip?

**Comment by ignatov** [comment] 2016-02-09 20:40
@saleyn Everything works fine for me:
<img width="1201" alt="screenshot 2016-02-09 23 39 29" src="https://cloud.githubusercontent.com/assets/426890/12929895/6d273fb2-cf86-11e5-9968-a52a729a11da.png">
Please see the artifacts popup.

**Comment by saleyn** [comment] 2016-02-09 23:28
Ah, thanks, that wasn't obvious!
