### ISSUE TITLE
jdk1.8 change to jdk1.7 problem

### ISSUE THREAD

**Issue by fatherican** [ignatov/intellij-erlang#736] opened 2016-04-28 10:27 UTC
When the Jdk verion from 1.8 changed to 1.7, the  idea can't compile java code.
the exception below:

Error:Internal error: (java.lang.UnsupportedClassVersionError) com/intellij/execution/ExecutionException : Unsupported major.minor version 52.0
java.lang.UnsupportedClassVersionError: com/intellij/execution/ExecutionException : Unsupported major.minor version 52.0
    at java.lang.ClassLoader.defineClass1(Native Method)
    at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
    at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
    at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
    at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
    at org.intellij.erlang.jps.builder.ErlangBuilderService.createBuilders(ErlangBuilderService.java:38)
    at org.jetbrains.jps.incremental.BuilderRegistry.<init>(BuilderRegistry.java:53)
    at org.jetbrains.jps.incremental.BuilderRegistry.<init>(BuilderRegistry.java:33)
    at org.jetbrains.jps.incremental.BuilderRegistry$Holder.<clinit>(BuilderRegistry.java:36)
    at org.jetbrains.jps.incremental.BuilderRegistry.getInstance(BuilderRegistry.java:43)
    at org.jetbrains.jps.cmdline.BuildRunner.runBuild(BuildRunner.java:132)
    at org.jetbrains.jps.cmdline.BuildSession.runBuild(BuildSession.java:294)
    at org.jetbrains.jps.cmdline.BuildSession.run(BuildSession.java:125)
    at org.jetbrains.jps.cmdline.BuildMain$MyMessageHandler$1.run(BuildMain.java:232)
    at org.jetbrains.jps.service.impl.SharedThreadPoolImpl$1.run(SharedThreadPoolImpl.java:44)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
    at java.util.concurrent.FutureTask.run(FutureTask.java:262)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:745)

**Comment by KronicDeth** [comment] 2016-06-03 03:13
I believe this is a duplicate of #727.  It has a lot of information on the fix in-progress, you may want to Subscribe to that issue too.

**Comment by ignatov** [comment] 2019-07-31 12:53
obsole?

**Closed by ignatov** 2019-07-31 12:53 UTC
