### ISSUE TITLE
One more variable resolve issue

### ISSUE THREAD

**Issue by ignatov** [ignatov/intellij-erlang#492] opened 2014-08-18 12:14 UTC
``` erlang
cases() ->
 if
   true -> X = 11;
   true -> X = 12
 end,
 case X of
   X -> ok;
   Z -> ok
 end.
```

Try to rename the variable X.

**Comment by kvakvs** [comment] 2019-08-01 09:09
This is a duplicate of #819

**Closed by kvakvs** 2019-08-01 09:09 UTC
