### ISSUE TITLE
Variable unbound incorrectly reported

### ISSUE THREAD

**Issue by paraparaman** [ignatov/intellij-erlang#855] opened 2019-01-07 13:40 UTC
![image](https://user-images.githubusercontent.com/29219562/50771136-af924700-12c4-11e9-9c51-fc17ba89c583.png)

idea report B is unbound!

**Comment by loxs** [comment] 2019-02-07 09:16
Also in cases like this. the `Friend` variable is both reported as not used and unbound:

<img width="792" alt="screenshot 2019-02-07 at 11 14 45" src="https://user-images.githubusercontent.com/162763/52401159-b5e53000-2ac9-11e9-9df3-d007de6e292a.png">

**Comment by ignatov** [comment] 2019-02-07 12:21
Hi, thanks for reporting, could you please provide a piece of code not a screen shot?

**Comment by loxs** [comment] 2019-02-07 12:48
Simplest snippet would be something like this:
```erlang
test_fun() ->
    case length(Lst = [1, 2, 3]) of
        3 -> Lst;
        _ -> not_3
    end.
```

**Comment by justintung** [comment] 2019-07-26 09:14
when variable was defined at case sub statement,will get the "unbound"message

**Comment by kvakvs** [comment] 2019-08-01 09:00
This is a duplicate of #819
Thank you for reporting

**Closed by kvakvs** 2019-08-01 09:00 UTC
