### ISSUE TITLE
Plugin does not detect variables usage in nested cases

### ISSUE THREAD

**Issue by brigadier** [ignatov/intellij-erlang#806] opened 2017-08-27 15:12 UTC
It's easier to illustrate this problem with examples.
works fine:
```erlang
f(X) ->
	case X of
		1 ->
			A = a,
			B = b;
		2 ->
			B = c,
			A = d
	end,
	{A, B}.
```

shows variables in the `case Y` as unused. in fact they are not:
```erlang
f(X, Y) ->
	case X of
		1 ->
			case Y of
				1 ->
					A = a,
					B = b;
				2 ->
					A = a1,
					B = b2
			end;

		2 ->
			B = c,
			A = d
	end,
	{A, B}.

```

**Comment by ignatov** [comment] 2017-08-27 19:34
Thanks for the repro.

**Comment by kvakvs** [comment] 2019-08-01 09:04
This is a duplicate of #819
Thank you for reporting

**Closed by kvakvs** 2019-08-01 09:04 UTC
Labels: duplicate
