### ISSUE TITLE
Escaping in string literals

### ISSUE THREAD

**Issue by deadok22** [ignatov/intellij-erlang#442] opened 2014-03-03 10:41 UTC
Try typing something like this:

``` erlang
ok() ->
  {200, [], "OK\n"}.
```

Right after you type OK\n the string literal is not highlighted as if it was a string literal.

**Comment by kvakvs** [comment] 2019-08-01 11:46
Duplicate of #808
Last string literal in the file sometimes is not recognized as a string literal.

**Closed by kvakvs** 2019-08-01 11:46 UTC
