### ISSUE TITLE
Run configuration doesn't compile project.

### ISSUE THREAD

**Issue by MIC132** [ignatov/intellij-erlang#695] opened 2015-11-07 15:30 UTC
So I recently switched to IDEA 15, and now have strange problem with my Erlang projects.

The .erl files are not getting compiled into .bean files when I run a run configuration, which causes it to throw an error that the main function that should be run is undefined.

My program basically looks like this:
```
-module(testFile).

-export([test/0]).

test() -> io:fwrite("test").
```

I then go into run configuration, add new Erlang Application, select module, set "Module and Function" to "testFile test", and it will fail when I try to run it.

The problem isn't with the erlang installation itself (I think), since if I open the console (from IDE) in that location, c(testFile). and then testFile:test(). work ok.

The folders "out", "production"/"test" and then "<project name>" are created, but they are empty.

**Comment by deadok22** [comment] 2015-11-07 15:48
Hi @MIC132, which plugin build are you using? I've fixed a similar problem recently, so try the latest available build from https://github.com/ignatov/intellij-erlang/releases.

**Comment by MIC132** [comment] 2015-11-07 17:48
I downloaded the latest version today after encountering the bug, so I think this isn't it.
I might try reinstalling the plugin again later though.

**Comment by deadok22** [comment] 2015-11-08 11:09
@MIC132 I've just tried to reproduce the problem with no success, unfortunately. Could you share your project, and explain steps to reproduce more thoroughly?

**Comment by MIC132** [comment] 2015-11-08 11:16
Here is my project, along with the crash log inside (github doesn't support zips):
http://www.mediafire.com/download/04dr86napkjrgn3/ErlangPractice.7z

As for reproduction, the project should include a run configuration (if I remember correctly they should be stored in .idea) so just try to run that. If it doesn't, make a run configuration of type "Erlang Application", as Module choose "ErlangPractice", and then as "Module and function" set "myprogram test", and just run that.

If it works then I have no idea where the problem might be, as I completely reinstalled both the plugin (using the release from github) and my erlang OTP installation.

**Comment by deadok22** [comment] 2015-11-09 11:48
The latest release build (available via plugin repository) contains this bug, indeed.

Latest build from https://github.com/ignatov/intellij-erlang/releases works fine though. Are you sure you've tried it when I asked you to do so? Please, re-check and let me know if it works.

Anyway, we'll update the build in plugin repository.

**Comment by MIC132** [comment] 2015-11-09 11:53
I downloaded the latest build from that link twice, and uninstalled the repo version before installing it.
Though perhaps the bug lies in something that's not removed properly when uninstalling (doubtful).
I guess I'll just do a full reinstall of Idea and wipe all settings.

**Comment by deadok22** [comment] 2015-11-09 12:06
It seems, I've figure out what's going on here. You've removed your build output manually, and run your run configuration without making changes to your source files. That way, the plugin considers your binaries up-to-date, and doesn't rebuild them.

Please, try changing a line in ```myprogram.erl``` and see if it builds upon running your run configuration.

You can use 'Build' -> 'Rebuild Project' action if you want to rebuild your binaries completely and in case you removed them.

**Comment by deadok22** [comment] 2015-11-09 12:09
In fact, it's a common behavior for the IntelliJ platform. If you remove .class files from java build output, it won't build them either.

Let me know if that's the case.

**Comment by MIC132** [comment] 2015-11-09 12:11
I did that once, by accident, but that was two test projects and two plugin
reinstalls ago I'm afraid.

The particular project I sent you didn't compile the first time I ever ran
it's run config. It was freshly created.

**Comment by Startigers** [comment] 2015-11-09 12:32
Is your project from Type=ERLANG_MODULE and has the facet erlang?

Check your project iml file:
```xml
<module type="ERLANG_MODULE" version="4">
  <component name="FacetManager">
    <facet type="erlang" name="Erlang">
      <configuration />
    </facet>
  </component>
<!-- .... -->
```
Or even easier, has the project root folder an red "e" icon?

**Comment by MIC132** [comment] 2015-11-09 12:37
It has the icon. It was created through "new project" -> "erlang".

Also I'd like to note you should have my .iml, it should have been in the
archive along with the rest of the project.

**Comment by Startigers** [comment] 2015-11-09 12:40
Sorry I don't have it. I am not **deadok22**. I only read this issue and thought I could help.

**Comment by deadok22** [comment] 2015-11-09 12:54
So, is it reproducible when you create a fresh new project? Could you try it out?

It matters that the project is new, because IntelliJ build system caches information about previous builds in a directory outside of the project.

**Comment by MIC132** [comment] 2015-11-09 15:24
Sorry, I didn't realize there were two people responding, as I was reading the responses from my mails, and there are no avatars there.

Yes, it's fully reproducible with a fresh new project for me. That's after reinstalling erlang, and the plugin. Only thing I didn't do is wiping my Intelij Idea settings completely, which I'll have to try by the looks of it.

**Comment by deadok22** [comment] 2015-11-09 15:37
@Startigers could you try to reproduce it?

**Comment by MIC132** [comment] 2015-11-09 18:07
Small update. I just checked, and even if I do any changes to my .erl file, and then click "build" or "rebuild project"  the log just says "Sources/Test sources is up to date(...)".

**Comment by Startigers** [comment] 2015-11-09 18:38
I will try it tomorrow.

**Comment by Startigers** [comment] 2015-11-10 08:53
I tried it and the beam was build. So I don't have a problem with this configuration and project.
The only thing I changed was the Erlang version cause I am still on version 17.5

```Erlang
/opt/erlang/17.5/bin/erl -pa /home/startigers/zzz/ErlangPractice/out/production/ErlangPractice -pa /home/startigers/zzz/ErlangPractice -eval myprogram:test(). -s init stop -noshell
Test
```

**Comment by MIC132** [comment] 2015-11-10 09:12
Well, looks like full reinstall is in order. I'll report if that helps when
I get around to doing it.

**Comment by Startigers** [comment] 2015-11-10 09:19
If you check the plugin version which version do you have?
File->Settings->Plugins->Erlang-> Below the Uninstall button
In my case it is Version 0.6.837.

Did you try an other Erlang Version, for instance 17?

**Comment by MIC132** [comment] 2015-11-10 09:22
Yeah,  I have that version of plugin. At least as far as I remember. Can't
check now.

I didn't try different erlang version though.

**Comment by deadok22** [comment] 2015-11-10 11:16
Thank you guys for your help.

I have an idea on what could go wrong with your installation, @MIC132. Which file did you point to when you installed the plugin from https://github.com/ignatov/intellij-erlang/releases? If it was a jar file, than this is it, you should have used a whole zip.

**Comment by MIC132** [comment] 2015-11-10 11:19
No, I used the downloaded zip as-is, with no unpacking.
I doubt it would install at all otherwise.

**Comment by deadok22** [comment] 2015-11-10 11:20
It would. But using some functionality would lead to errors.

**Comment by deadok22** [comment] 2015-11-10 11:21
Oh, forgot to mention, that the issue has nothing to do with Erlang version. So there's no point in trying other versions to reproduce the issue.

**Comment by Lyoko-Jeremie** [comment] 2015-11-11 04:00
I got the same problem yesterday.(in windows 7)
I move the project to archlinux 's idea, it not happend.
so, maybe it only happend in windows?

When I see the Make Message Both platform have some diff.
In Windows:
````
Information:erlc: Sources is up to date for module "deviceinfocache".
Information:erlc: Test sources is up to date for module "deviceinfocache".
Information:erlc: Copy D:\Code\Erlang\smartclassroom\deviceinfocache\out\production\deviceinfocache\device_info_cache.app to D:\Code\Erlang\smartclassroom\deviceinfocache\out\production\deviceinfocache
Information:erlc: Copy D:\Code\Erlang\smartclassroom\deviceinfocache\out\test\deviceinfocache\device_info_cache.app to D:\Code\Erlang\smartclassroom\deviceinfocache\out\test\deviceinfocache
Information:2015/11/11 11:55 - Compilation completed successfully in 460ms
````

In Linux
````
Information:erlc: Compile source code for module "deviceinfocache".
Information:erlc: /lib/erlang/bin/erlc -pa 
/home/jeremie/git/smartclassroom/deviceinfocache/out/production/deviceinfocache 
-pa /home/jeremie/git/smartclassroom/deviceinfocache +debug_info 
/home/jeremie/git/smartclassroom/deviceinfocache/src/device_state_inquire_server.erl 
/home/jeremie/git/smartclassroom/deviceinfocache/src/device_state_manager_server.erl 
/home/jeremie/git/smartclassroom/deviceinfocache/src/device_info_cache_app.erl 
/home/jeremie/git/smartclassroom/deviceinfocache/src/device_cache_thread_sup.erl 
/home/jeremie/git/smartclassroom/deviceinfocache/src/device_cache_thread.erl 
/home/jeremie/git/smartclassroom/deviceinfocache/src/device_info_cache_sup.erl
Information:erlc: Compile tests for module "deviceinfocache".
Information:erlc: /lib/erlang/bin/erlc -pa 
/home/jeremie/git/smartclassroom/deviceinfocache/out/production/deviceinfocache 
-pa /home/jeremie/git/smartclassroom/deviceinfocache +debug_info -DTEST 
/home/jeremie/git/smartclassroom/deviceinfocache/src/device_state_inquire_server.erl 
/home/jeremie/git/smartclassroom/deviceinfocache/src/device_state_manager_server.erl 
/home/jeremie/git/smartclassroom/deviceinfocache/src/device_info_cache_app.erl 
/home/jeremie/git/smartclassroom/deviceinfocache/src/device_cache_thread_sup.erl 
/home/jeremie/git/smartclassroom/deviceinfocache/src/device_cache_thread.erl 
/home/jeremie/git/smartclassroom/deviceinfocache/src/device_info_cache_sup.erl
Information:erlc: Copy 
/home/jeremie/git/smartclassroom/deviceinfocache/out/production/deviceinfocache/device_info_cache.app 
to 
/home/jeremie/git/smartclassroom/deviceinfocache/out/production/deviceinfocache
Information:erlc: Copy 
/home/jeremie/git/smartclassroom/deviceinfocache/out/test/deviceinfocache/device_info_cache.app 
to 
/home/jeremie/git/smartclassroom/deviceinfocache/out/test/deviceinfocache
Information:11/11/15 11:57 AM - Compilation completed successfully with 
1 warning in 5s 8ms
/home/jeremie/git/smartclassroom/deviceinfocache/src/device_state_manager_server.erl
Warning:(109, -1) erlc: variable 'DeviceInfoStruct' is unused

````


When windows,  It lost some step that call erlc make file.

**Comment by Lyoko-Jeremie** [comment] 2015-11-11 04:19
Just now, 
I clear resintall IDEA 15.0 and download erlang plugin v0.6.837 from https://github.com/ignatov/intellij-erlang/releases,And install it from disk.
Rebuild project, The problem still .

**Comment by MIC132** [comment] 2015-11-13 16:46
Any progress on this issue?

**Comment by deadok22** [comment] 2015-11-13 17:26
No progress so far. I'll try to reproduce it on windows and we'll see what we can do.

**Comment by deadok22** [comment] 2015-11-13 17:26
Guys, does it compile your project via 'Rebuild Project' action?

**Comment by MIC132** [comment] 2015-11-13 17:44
Not for me. And I alredy mentioned it, I think.

**Comment by deadok22** [comment] 2015-11-13 17:46
@MIC132 I'm sorry I missed it. Thank you.

**Comment by MIC132** [comment] 2015-11-15 16:13
I just got around to doing a full reinstall of Intelij Idea, deleteing all settings, etc. I could find.
The problem still remains the same (with new project created after reinstal).

**Comment by deadok22** [comment] 2015-11-20 12:49
Hi @MIC132,

I'm sorry it took so long. I've reproduced the issue on Windows. It's not yet clear what the problem is, I'll let you know once I figure it out.

Thanks!

**Comment by deadok22** [comment] 2015-11-20 22:05
@ignatov could you set up our CI server to run compilation tests on Windows as well?

**Comment by deadok22** [comment] 2015-11-20 22:06
@MIC132 thank you very much for your help with resolving this issue.

**Closed by deadok22** 2015-11-20 22:06 UTC

**Comment by ignatov** [comment] 2015-11-20 22:14
@deadok22 Will try, but after my vacations, ping me on December 11-12, OK?

**Comment by deadok22** [comment] 2015-11-20 22:34
@ignatov ok, will do.

**Comment by MIC132** [comment] 2015-11-23 17:39
Is there still no release that includes this fix?

**Comment by deadok22** [comment] 2015-11-23 17:49
A release will only be available when @ignatov is back from his vacation. Until then, you can build it from source.

**Comment by MIC132** [comment] 2015-12-26 16:34
When can we expect the new release?
As far as I can see there is still no release that includes this fix. It was said that it would be available when @ignatov returns from vacation, but that was supposed to be around 12-14 December.

**Comment by ignatov** [comment] 2015-12-26 20:39
Sorry guys, I'm a bit busy these days. I'm going to publish a new build ASAP. Merry Christmas and happy New Year.

**Comment by MIC132** [comment] 2015-12-26 21:51
Merry Christmas to you too.
No problem, I just wanted to be sure the build is coming.

**Comment by ignatov** [comment] 2015-12-26 22:56
Feel free to download and install manually the latest build from: https://teamcity.jetbrains.com/viewType.html?buildTypeId=IntellijIdeaPlugins_IntellijErlang_Tests

**Comment by stableShip** [comment] 2016-01-20 04:38
using ![image](https://cloud.githubusercontent.com/assets/2979404/12440020/54e77990-bf72-11e5-8ddf-ba4fd6bde618.png)

erlang_plugin: snapshots 
![image](https://cloud.githubusercontent.com/assets/2979404/12440040/8431c6ce-bf72-11e5-8fb3-749723e99bdc.png)

beam File still not be created in out/production/myproject/

**Comment by stableShip** [comment] 2016-01-20 06:56
my mistake
 check off this 
![image](https://cloud.githubusercontent.com/assets/2979404/12441820/f5175f3a-bf85-11e5-82ef-695a5ff6d9a8.png)
everything work fine!

**Comment by MIC132** [comment] 2016-02-19 12:01
Was the newest version still not released to Inteliji repo? The update info shows that latest version is from November 2015.
I'm using a manually installed build, but I'd prefer to be able to update it normally.

**Comment by ildar2** [comment] 2016-07-20 09:29
Having exactly the same problem: on compilation Intellij creates empty out/production/Ejabberd folder.
I've tried IJ 14, 15 and 16 builds, Erlang plugins both official and from teamcity, tried launching IDE as administrator - nothing helped

Erlang plugin version: 0.8.893
IntelliJ IDEA 2016.2
Build #IC-162.1121.32, built on July 9, 2016

**Comment by deadok22** [comment] 2016-07-20 09:53
@ildar2, it would be awesome if you filed a new issue and added problem description and, ideally, steps to reproduce. Thank you.

**Comment by ildar2** [comment] 2016-07-20 10:51
The solution is rather simple: you have to set source folder in project settings:

![no beam solution](https://cloud.githubusercontent.com/assets/13849510/16984096/1e4c1fe6-4e9a-11e6-96dd-ad23a62128e9.png)

**Comment by kagan94** [comment] 2017-06-12 15:06
I also faced with this issue.

How I solved it:
- created a new project from the scratch and copied all needed scripts
- recompiled (rebuild) modules

Smth was wrong with settings in the project...
